# src/Site/Bundle/MainBundle/Resources/config/validation.yml
Site\MainBundle\Entity\Project:
    properties:
        title:
            - NotBlank:
                message: "Название проекта не может быть пустым"
Site\MainBundle\Entity\Page:
    properties:
        title:
            - NotBlank:
                message: "Заголовок страницы не может быть пустым"
Site\MainBundle\Entity\Service:
    properties:
        title:
            - NotBlank:
                message: "Название услуги не может быть пустым"

Site\MainBundle\Entity\Partners:
    properties:
        position:
            - Type:
                type: integer
                message: "Вы некорректно ввели порядковый номер!"
            - GreaterThan:
                value: -1
                message: "Порядковый номер не может быть меньше нуля!"
            - NotBlank:
                message: "Вы не ввели порядковый номер!"
        name:
            - NotBlank:
                message: "Вы не ввели название!"
            - Length:
                max: 100
        link:
            - Url:
                message: "Вы ввели некорректную ссылку (http:// обязательно)!"

Site\MainBundle\Form\Feedback:
    properties:
        name:
            - NotBlank:
                message: "Вы не ввели имя"
        email:
            - NotBlank:
                message: "Вы не ввели email"
            - Email:
                message: "Вы неверно заполнили email"
        message:
            - NotBlank:
                message: "Вы не ввели сообщение"