frontend_homepage:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_feedback:
    path:     /feedback
    defaults: { _controller: "SiteMainBundle:Frontend/Main:feedback" }
    methods:  POST

frontend_work:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/work.yml"
    prefix: /nashi-raboty

frontend_blog:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/news.yml"
    prefix: /blogh

frontend_page_contacts:
    path:     /kontakty
    defaults: { _controller: "SiteMainBundle:Frontend/Main:contacts" }

frontend_page_about:
    path:     /o-nas
    defaults: { _controller: "SiteMainBundle:Frontend/About:index" }

frontend_page_price:
    path:     /uslughi
    defaults: { _controller: "SiteMainBundle:Frontend/Price:index" }

frontend_page_index:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_sitemap_index:
    path:     /sitemap/sitemap.xml
    defaults: { _controller: "SiteMainBundle:Frontend/Main:sitemap" }    