frontend_news_all:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/News:index" }

frontend_news_one:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/News:one" }